- hosts: "{{ h }}"

  vars:
    ldaps_port: 636
    phpldapadmin_port: 8443
    casino_port: 443
    ldap_dn: dc=forgeservicelab,dc=fi
    binder_dn: "cn=binder,ou=accounts,{{ ldap_dn }}"
    pwdchanger_dn: "cn=pwdchanger,ou=accounts,{{ ldap_dn }}"


  vars_files:
    # secrets.yml must define ldap_admin_password, binder_password and pwdchanger_password
    - files/secrets.yml

  pre_tasks:
    - name: disable selinux in configuration (takes effect after reboot)
      selinux:
        state: disabled
    - name: actually turn selinux off
      shell: setenforce permissive
      ignore_errors: True

  roles:
    - role: forge_hostname

    - role: ansible-role-repo-epel

    - role: openldap_server
      openldap_server_domain_name: "{{ ansible_fqdn }}"
      openldap_server_rootpw: "{{ ldap_admin_password }}"
      openldap_server_enable_ssl: true
      openldap_server_country: FI
      openldap_server_state: Uusimaa
      openldap_server_location: Helsinki
      openldap_server_organization: DIGILE
      openldap_server_dn: "{{ ldap_dn }}"
      openldap_server_binder_dn: "{{ binder_dn }}"
      openldap_server_binder_password: "{{ binder_password }}"
      openldap_server_pwdchanger_dn: "{{ pwdchanger_dn }}"
      openldap_server_pwdchanger_password: "{{ pwdchanger_password }}"

    # - role: openldap_populator
    #   entities_file: entities/digile.yml
    #   openldap_server_dn: "{{ ldap_dn }}"
    #   openldap_server_rootpw: "{{ ldap_admin_password }}"

    - role: phpldapadmin
      phpldapadmin_port: "{{ phpldapadmin_port }}"
      phpldapadmin_dn: "{{ ldap_dn }}"
      phpldapadmin_ldap_port: "{{ ldaps_port }}"
      phpldapadmin_ldap_uri: "ldaps://127.0.0.1"
      phpldapadmin_accounts_subtree: 'ou=accounts'
      phpldapadmin_binder_dn: "{{ binder_dn }}"
      phpldapadmin_binder_password: "{{ binder_password }}"
      tags: phpldapadmin


    - role: mstrisoline.ruby-builder
      ruby_builder_ruby_version: '1.9.3-p484'

    - role: casino
      casino_port: "{{ casino_port }}"
      casino_ldap_host: localhost
      casino_ldap_port: "{{ ldaps_port }}"
      casino_ldap_users_dn: "ou=accounts,{{ ldap_dn }}"
      casino_ldap_username_attribute: cn
      casino_ldap_binder_dn: "{{ binder_dn }}"
      casino_ldap_binder_password: "{{ binder_password }}"
      tags: cas

    - role: synchronizer

    # if you want to user forge_users role, your secrets.yml must contain
    # gitlab_private_token to get public keys of users from git.
    #- role: forge_users
    #  forge_users_private_token: "{{ gitlab_private_token }}"
    #  forge_users_list:
    #    - jrodrigu
    #    - tkarasek
    #    - erno.koliseva
    #    - tero.elonen
    #  tags: users

  tasks:
    - shell: lokkit -p {{ item }}:tcp
      with_items:
        - "{{ ldaps_port }}"
        - "{{ phpldapadmin_port }}"
        - "{{ casino_port }}"
      # CentOS 7 has iptables off by default
      when:
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

  post_tasks:
    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ phpldapadmin_port }}/phpldapadmin to add users"
    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ casino_port }} to see the CASino interface"
