- hosts: "{{ target }}"

  vars:
    ldaps_port: 636
    phpldapadmin_port: 8443
    casino_port: 443
    ldap_dn: dc=forgeservicelab,dc=fi
    binder_dn: "cn=binder,ou=accounts,{{ ldap_dn }}"
    syncer_dn: "cn=syncer,ou=accounts,{{ ldap_dn }}"
    pwdchanger_dn: "cn=pwdchanger,ou=accounts,{{ ldap_dn }}"


  vars_files:
    # secrets.yml must define ldap_admin_password, binder_password and pwdchanger_password as well as any
    # other needed identity variables.
    - secrets.yml

  pre_tasks:
    - name: disable selinux in configuration (takes effect after reboot)
      selinux:
        state: disabled
    - name: actually turn selinux off
      shell: setenforce permissive
      ignore_errors: True

  roles:
    - role: forge_hostname

    - role: forge_ssl

    - role: ansible-role-repo-epel

    - role: openldap_server
      openldap_server_domain_name: "{{ ansible_fqdn }}"
      openldap_server_rootpw: "{{ ldap_admin_password }}"
      openldap_server_enable_ssl: true
      openldap_server_country: FI
      openldap_server_state: Uusimaa
      openldap_server_location: Helsinki
      openldap_server_organization: DIGILE
      openldap_server_dn: "{{ ldap_dn }}"
      openldap_server_binder_dn: "{{ binder_dn }}"
      openldap_server_binder_password: "{{ binder_password }}"
      openldap_server_syncer_dn: "{{ syncer_dn }}"
      openldap_server_syncer_password: "{{ syncer_password }}"
      openldap_server_pwdchanger_dn: "{{ pwdchanger_dn }}"
      openldap_server_pwdchanger_password: "{{ pwdchanger_password }}"
      openldap_server_cacert: roles/forge_ssl/files/forgeservicelab.fi.crt.chain
      openldap_server_cert: roles/forge_ssl/files/forgeservicelab.fi.crt
      openldap_server_key: forgeservicelab.fi.key
      upload_certs: True

    - role: phpldapadmin
      phpldapadmin_port: "{{ phpldapadmin_port }}"
      phpldapadmin_dn: "{{ ldap_dn }}"
      phpldapadmin_ldap_port: "{{ ldaps_port }}"
      phpldapadmin_ldap_uri: "ldaps://127.0.0.1"
      phpldapadmin_accounts_subtree: 'ou=accounts'
      phpldapadmin_binder_dn: "{{ binder_dn }}"
      phpldapadmin_binder_password: "{{ binder_password }}"
      phpldapadmin_ssl_ca_cert: "{{ forge_ssl_cert_chain }}"
      phpldapadmin_ssl_cert: "{{ forge_ssl_cert }}"
      phpldapadmin_ssl_key: "{{ forge_ssl_key }}"
      tags: phpldapadmin


    - role: mstrisoline.ruby-builder
      ruby_builder_ruby_version: '1.9.3-p484'

    - role: casino
      casino_repo: "https://{{ forge_git_usr }}:{{ forge_git_pwd }}@git.forgeservicelab.fi/forge/casinoapp.git"
      casino_version: forge
      casino_port: "{{ casino_port }}"
      casino_ldap_host: localhost
      casino_ldap_port: "{{ ldaps_port }}"
      casino_ldap_users_dn: "ou=accounts,{{ ldap_dn }}"
      casino_ldap_username_attribute: cn
      casino_ldap_binder_dn: "{{ binder_dn }}"
      casino_ldap_binder_password: "{{ binder_password }}"
      casino_ssl_ca_cert: "{{ forge_ssl_cert_chain }}"
      casino_ssl_cert: "{{ forge_ssl_cert }}"
      casino_ssl_key: "{{ forge_ssl_key }}"
      casino_db_name: "{{ casino_db }}"
      casino_db_host: dbserver.forgeservicelab.fi
      casino_db_username: "{{ casino_db_usr }}"
      casino_db_password: "{{ casino_db_pwd }}"
      tags: cas

    - role: simplesamlphp
      simplesamlphp_admin_password: "{{ saml_admin_password }}"
      simplesamlphp_ldap_binder_password: "{{ binder_password }}"
      simplesamlphp_suburi: ""
      simplesamlphp_fqdn: idp.forgeservicelab.fi
      tags: idp

    - role: ltb_password_app
      ltb_password_app_repo: "https://{{ forge_git_usr }}:{{ forge_git_pwd }}@git.forgeservicelab.fi/forge/forge-password-change.git"
      ltb_ldap_url: "ldaps://127.0.0.1"
      ltb_ldap_binddn: "{{ pwdchanger_dn }}"
      ltb_ldap_bindpw: "{{ pwdchanger_password }}"
      ltb_recaptcha_pub: "{{ recaptcha_public_key }}"
      ltb_recaptcha_priv: "{{ recaptcha_private_key }}"
      tags: password

    - role: firewallder
      services_dir: ../../../files/services
      zones_dir: ../../../files/zones
      tags: firewall

    # if you want to user forge_users role, your secrets.yml must contain
    # gitlab_private_token to get public keys of users from git.
    #- role: forge_users
    #  forge_users_private_token: "{{ gitlab_private_token }}"
    #  forge_users_list:
    #    - jrodrigu
    #    - tkarasek
    #    - erno.koliseva
    #    - tero.elonen
    #  tags: users

  tasks:
    - shell: lokkit -p {{ item }}:tcp
      with_items:
        - "{{ ldaps_port }}"
        - "{{ phpldapadmin_port }}"
        - "{{ casino_port }}"
      # CentOS 7 has iptables off by default
      when:
        ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

  post_tasks:
    - name: Upload dynamic list syncer script
      template:
        src: files/dynlist_sync.py
        dest: /opt/dynlist_sync.py
        owner: ldap
        group: ldap
        mode: 0755
      tags: cron

    - name: Set up dynamic list sync cron job
      cron:
        name: Synchronize dynamic LDAP lists
        minute: '*/5'
        job: /opt/dynlist_sync.py
        user: ldap
      tags: cron

    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ phpldapadmin_port }}/phpldapadmin to add users"
    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ casino_port }} to see the CASino interface"
    - debug:
        msg: "visit https://{{ simplesamlphp_fqdn }}:443 to see the IdP interface"
