- hosts: "{{ h }}"

  vars:
    ldaps_port: 636
    phpldapadmin_port: 8443
    casino_port: 443
    ldap_dn: dc=forgeservicelab,dc=fi
    binder_dn: "cn=binder,ou=people,{{ ldap_dn }}"


  vars_files:
    # secrets.yml must define ldap_admin_password and binder_password
    - secrets.yml

  pre_tasks:
    - shell: yum --enablerepo epel version
      register: verify_epel_installed
      ignore_errors: True

    - name: remove installed libyaml as it conflicts with EPEL libyaml
      yum: name=libyaml state=removed
      when: verify_epel_installed|failed

  roles:
      # $ git clone https://git.forgeservicelab.fi/ansible-roles/forge_hostname.git
    - role: forge_hostname

      # $ sudo ansible-galaxy install goozbach.EPEL
    - role: goozbach.EPEL
      when: verify_epel_installed|failed

      # $ git clone https://git.forgeservicelab.fi/ansible-roles/openldap_server.git
    - role: openldap_server
      openldap_server_domain_name: "{{ ansible_fqdn }}"
      openldap_server_rootpw: "{{ ldap_admin_password }}"
      openldap_server_enable_ssl: true
      openldap_server_country: FI
      openldap_server_state: Uusimaa
      openldap_server_location: Helsinki
      openldap_server_organization: JulkICTLAB
      openldap_server_dn: "{{ ldap_dn }}"
      openldap_server_binder_dn: "{{ binder_dn }}"
      openldap_server_binder_password: "{{ binder_password }}"

      # $ git clone https://git.forgeservicelab.fi/ansible-roles/phpldapadmin.git
    - role: phpldapadmin
      phpldapadmin_port: "{{ phpldapadmin_port }}"
      phpldapadmin_dn: "{{ ldap_dn }}"
      phpldapadmin_ldap_port: "{{ ldaps_port }}"
      phpldapadmin_ldap_uri: "ldaps://127.0.0.1"
      phpldapadmin_binder_dn: "{{ binder_dn }}"
      phpldapadmin_binder_password: "{{ binder_password }}"


      # $ sudo ansible-galaxy install mstrisoline.ruby-builder
    - role: mstrisoline.ruby-builder
      ruby_builder_ruby_version: '1.9.3-p484'

      # $ git clone https://git.forgeservicelab.fi/ansible-roles/casino.git
    - role: casino
      casino_port: "{{ casino_port }}"
      casino_ldap_host: localhost
      casino_ldap_port: "{{ ldaps_port }}"
      casino_ldap_users_dn: "ou=people,{{ ldap_dn }}"
      casino_ldap_username_attribute: cn
      casino_ldap_binder_dn: "{{ binder_dn }}"
      casino_ldap_binder_password: "{{ binder_password }}"

      # $ git clone https://git.forgeservicelab.fi/ansible-roles/forge_users.git
    - role: forge_users
      forge_users_private_token: "{{ gitlab_private_token }}"
      forge_users_list:
        - jrodrigu
        - tkarasek
        - erno.koliseva
        - tero.elonen
      tags: users

  tasks:
    - shell: lokkit -p {{ ldaps_port }}:tcp
    - shell: lokkit -p {{ phpldapadmin_port }}:tcp
    - shell: lokkit -p {{ casino_port }}:tcp

  post_tasks:
    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ phpldapadmin_port }}/phpldapadmin to add users"
    - debug:
        msg: "visit https://{{ ansible_fqdn }}:{{ casino_port }} to see the CASino interface"
