- src: git+https://git.forgeservicelab.fi/ansible-roles/forge_hostname.git
- src: goozbach.EPEL
- src: mstrisoline.ruby-builder
#- src: git+https://git.forgeservicelab.fi/ansible-roles/forge_users.git
- src: git+https://git.forgeservicelab.fi/ansible-roles/casino.git
- src: git+https://git.forgeservicelab.fi/ansible-roles/openldap_server.git
- src: git+https://git.forgeservicelab.fi/ansible-roles/phpldapadmin.git
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/synchronizer.git
- src: https://github.com/geerlingguy/ansible-role-repo-epel
