- src: git+https://git.forgeservicelab.fi/ansible-roles/forge_hostname.git
- src: goozbach.EPEL
- src: mstrisoline.ruby-builder
- src: git+https://git.forgeservicelab.fi/ansible-roles/forge_users.git
- src: git+https://git.forgeservicelab.fi/ansible-roles/casino.git
